# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'galycDialog.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_galycDialog(object):
    def setupUi(self, galycDialog):
        galycDialog.setObjectName("galycDialog")
        galycDialog.resize(505, 601)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/images/galyc.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        galycDialog.setWindowIcon(icon)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(galycDialog)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.loginLayout = QtWidgets.QHBoxLayout()
        self.loginLayout.setObjectName("loginLayout")
        self.label_10 = QtWidgets.QLabel(galycDialog)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.loginLayout.addWidget(self.label_10)
        self.loginLine = QtWidgets.QLineEdit(galycDialog)
        self.loginLine.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.loginLine.setObjectName("loginLine")
        self.loginLayout.addWidget(self.loginLine)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.loginLayout.addItem(spacerItem)
        self.verticalLayout_6.addLayout(self.loginLayout)
        self.tabWidget = QtWidgets.QTabWidget(galycDialog)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.tabWidget.setFont(font)
        self.tabWidget.setToolTip("")
        self.tabWidget.setObjectName("tabWidget")
        self.comptesTab = QtWidgets.QWidget()
        self.comptesTab.setObjectName("comptesTab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.comptesTab)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_17 = QtWidgets.QLabel(self.comptesTab)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_2.addWidget(self.label_17)
        spacerItem1 = QtWidgets.QSpacerItem(20, 68, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.compteButton = QtWidgets.QPushButton(self.comptesTab)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.compteButton.setFont(font)
        self.compteButton.setObjectName("compteButton")
        self.horizontalLayout_6.addWidget(self.compteButton)
        spacerItem2 = QtWidgets.QSpacerItem(78, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        spacerItem3 = QtWidgets.QSpacerItem(20, 118, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.tabWidget.addTab(self.comptesTab, "")
        self.groupesTab = QtWidgets.QWidget()
        self.groupesTab.setObjectName("groupesTab")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupesTab)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_13 = QtWidgets.QLabel(self.groupesTab)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_8.addWidget(self.label_13)
        self.label_12 = QtWidgets.QLabel(self.groupesTab)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_8.addWidget(self.label_12)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.totalList = QtWidgets.QListWidget(self.groupesTab)
        self.totalList.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.totalList.setObjectName("totalList")
        self.horizontalLayout_10.addWidget(self.totalList)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.groupList = QtWidgets.QListWidget(self.groupesTab)
        self.groupList.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.groupList.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.groupList.setObjectName("groupList")
        self.verticalLayout_7.addWidget(self.groupList)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.delButton = QtWidgets.QPushButton(self.groupesTab)
        self.delButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/images/remove.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.delButton.setIcon(icon1)
        self.delButton.setObjectName("delButton")
        self.horizontalLayout_9.addWidget(self.delButton)
        spacerItem4 = QtWidgets.QSpacerItem(168, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem4)
        self.verticalLayout_7.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10.addLayout(self.verticalLayout_7)
        self.verticalLayout_8.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.groupeButton = QtWidgets.QPushButton(self.groupesTab)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.groupeButton.setFont(font)
        self.groupeButton.setObjectName("groupeButton")
        self.horizontalLayout_8.addWidget(self.groupeButton)
        self.supprGroupeButton = QtWidgets.QPushButton(self.groupesTab)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.supprGroupeButton.setFont(font)
        self.supprGroupeButton.setObjectName("supprGroupeButton")
        self.horizontalLayout_8.addWidget(self.supprGroupeButton)
        self.verticalLayout_8.addLayout(self.horizontalLayout_8)
        self.tabWidget.addTab(self.groupesTab, "")
        self.servicesTab = QtWidgets.QWidget()
        self.servicesTab.setObjectName("servicesTab")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.servicesTab)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_14 = QtWidgets.QLabel(self.servicesTab)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_10.addWidget(self.label_14)
        self.label_16 = QtWidgets.QLabel(self.servicesTab)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_10.addWidget(self.label_16)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.totalServiceList = QtWidgets.QListWidget(self.servicesTab)
        self.totalServiceList.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.totalServiceList.setObjectName("totalServiceList")
        self.horizontalLayout_13.addWidget(self.totalServiceList)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.serviceList = QtWidgets.QListWidget(self.servicesTab)
        self.serviceList.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.serviceList.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.serviceList.setObjectName("serviceList")
        self.verticalLayout_9.addWidget(self.serviceList)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.delServButton = QtWidgets.QPushButton(self.servicesTab)
        self.delServButton.setText("")
        self.delServButton.setIcon(icon1)
        self.delServButton.setObjectName("delServButton")
        self.horizontalLayout_14.addWidget(self.delServButton)
        spacerItem5 = QtWidgets.QSpacerItem(168, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem5)
        self.verticalLayout_9.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_13.addLayout(self.verticalLayout_9)
        self.verticalLayout_10.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.addServButton = QtWidgets.QPushButton(self.servicesTab)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.addServButton.setFont(font)
        self.addServButton.setObjectName("addServButton")
        self.horizontalLayout_11.addWidget(self.addServButton)
        self.supprServButton = QtWidgets.QPushButton(self.servicesTab)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.supprServButton.setFont(font)
        self.supprServButton.setObjectName("supprServButton")
        self.horizontalLayout_11.addWidget(self.supprServButton)
        self.verticalLayout_10.addLayout(self.horizontalLayout_11)
        self.tabWidget.addTab(self.servicesTab, "")
        self.eleveTab = QtWidgets.QWidget()
        self.eleveTab.setObjectName("eleveTab")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.eleveTab)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_19 = QtWidgets.QLabel(self.eleveTab)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_5.addWidget(self.label_19)
        self.groupBox_2 = QtWidgets.QGroupBox(self.eleveTab)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.prenomEleve = QtWidgets.QLineEdit(self.groupBox_2)
        self.prenomEleve.setText("")
        self.prenomEleve.setObjectName("prenomEleve")
        self.gridLayout_2.addWidget(self.prenomEleve, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 1, 0, 1, 1)
        self.nomEleve = QtWidgets.QLineEdit(self.groupBox_2)
        self.nomEleve.setObjectName("nomEleve")
        self.gridLayout_2.addWidget(self.nomEleve, 1, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 2, 0, 1, 1)
        self.loginEleve = QtWidgets.QLineEdit(self.groupBox_2)
        self.loginEleve.setObjectName("loginEleve")
        self.gridLayout_2.addWidget(self.loginEleve, 2, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 3, 0, 1, 1)
        self.classeEleve = QtWidgets.QLineEdit(self.groupBox_2)
        self.classeEleve.setObjectName("classeEleve")
        self.gridLayout_2.addWidget(self.classeEleve, 3, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 4, 0, 1, 1)
        self.mdpEleve = QtWidgets.QLineEdit(self.groupBox_2)
        self.mdpEleve.setObjectName("mdpEleve")
        self.gridLayout_2.addWidget(self.mdpEleve, 4, 1, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_2)
        self.verticalLayout_5.addWidget(self.groupBox_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.eleveButton = QtWidgets.QPushButton(self.eleveTab)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.eleveButton.setFont(font)
        self.eleveButton.setObjectName("eleveButton")
        self.horizontalLayout_4.addWidget(self.eleveButton)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.tabWidget.addTab(self.eleveTab, "")
        self.profTab = QtWidgets.QWidget()
        self.profTab.setObjectName("profTab")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.profTab)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_18 = QtWidgets.QLabel(self.profTab)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_3.addWidget(self.label_18)
        self.groupBox = QtWidgets.QGroupBox(self.profTab)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.prenomProf = QtWidgets.QLineEdit(self.groupBox)
        self.prenomProf.setObjectName("prenomProf")
        self.gridLayout.addWidget(self.prenomProf, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.nomProf = QtWidgets.QLineEdit(self.groupBox)
        self.nomProf.setObjectName("nomProf")
        self.gridLayout.addWidget(self.nomProf, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.loginProf = QtWidgets.QLineEdit(self.groupBox)
        self.loginProf.setObjectName("loginProf")
        self.gridLayout.addWidget(self.loginProf, 2, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.courrielProf = QtWidgets.QLineEdit(self.groupBox)
        self.courrielProf.setObjectName("courrielProf")
        self.gridLayout.addWidget(self.courrielProf, 3, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.profButton = QtWidgets.QPushButton(self.profTab)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.profButton.setFont(font)
        self.profButton.setObjectName("profButton")
        self.horizontalLayout.addWidget(self.profButton)
        spacerItem7 = QtWidgets.QSpacerItem(118, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem7)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.tabWidget.addTab(self.profTab, "")
        self.verticalLayout_6.addWidget(self.tabWidget)
        self.textSortie = QtWidgets.QTextBrowser(galycDialog)
        self.textSortie.setMinimumSize(QtCore.QSize(0, 0))
        self.textSortie.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.textSortie.setObjectName("textSortie")
        self.verticalLayout_6.addWidget(self.textSortie)
        self.progressBar = QtWidgets.QProgressBar(galycDialog)
        self.progressBar.setEnabled(True)
        self.progressBar.setMaximum(100)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_6.addWidget(self.progressBar)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.aboutButton = QtWidgets.QPushButton(galycDialog)
        self.aboutButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.aboutButton.setObjectName("aboutButton")
        self.horizontalLayout_2.addWidget(self.aboutButton)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem8)
        self.ipCombo = QtWidgets.QComboBox(galycDialog)
        self.ipCombo.setObjectName("ipCombo")
        self.horizontalLayout_2.addWidget(self.ipCombo)
        self.toolButton = QtWidgets.QPushButton(galycDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton.sizePolicy().hasHeightForWidth())
        self.toolButton.setSizePolicy(sizePolicy)
        self.toolButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/images/lock.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon2)
        self.toolButton.setIconSize(QtCore.QSize(25, 25))
        self.toolButton.setDefault(False)
        self.toolButton.setFlat(False)
        self.toolButton.setObjectName("toolButton")
        self.horizontalLayout_2.addWidget(self.toolButton)
        self.closeButton = QtWidgets.QPushButton(galycDialog)
        self.closeButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout_2.addWidget(self.closeButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)

        self.retranslateUi(galycDialog)
        self.tabWidget.setCurrentIndex(0)
        self.closeButton.clicked.connect(galycDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(galycDialog)

    def retranslateUi(self, galycDialog):
        _translate = QtCore.QCoreApplication.translate
        galycDialog.setWindowTitle(_translate("galycDialog", "Galyc - Gestion de l\'Annuaire du lycée"))
        self.label_10.setText(_translate("galycDialog", "Login à traiter : "))
        self.comptesTab.setToolTip(_translate("galycDialog", "<html><head/><body><p>Voir les informations d\'un compte.</p></body></html>"))
        self.label_17.setText(_translate("galycDialog", "Affiche les informations sur un compte "))
        self.compteButton.setText(_translate("galycDialog", "Voir les informations"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.comptesTab), _translate("galycDialog", "Comptes"))
        self.groupesTab.setToolTip(_translate("galycDialog", "<html><head/><body><p>Ajouter ou enlever des groupes à un utilisateur.</p></body></html>"))
        self.label_13.setText(_translate("galycDialog", "Ajoute ou supprime des groupes secondaires à un utilisateur"))
        self.label_12.setText(_translate("galycDialog", "Double-cliquer pour sélectionner des groupes à traiter :"))
        self.groupList.setSortingEnabled(True)
        self.groupeButton.setText(_translate("galycDialog", "Ajouter aux groupes"))
        self.supprGroupeButton.setText(_translate("galycDialog", "Supprimer des groupes"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.groupesTab), _translate("galycDialog", "Groupes"))
        self.label_14.setText(_translate("galycDialog", "Ajoute ou supprime des services à un professeur"))
        self.label_16.setText(_translate("galycDialog", "Double-cliquer pour sélectionner des groupes à traiter :"))
        self.serviceList.setSortingEnabled(True)
        self.addServButton.setText(_translate("galycDialog", "Ajouter des services"))
        self.supprServButton.setText(_translate("galycDialog", "Supprimer des services"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.servicesTab), _translate("galycDialog", "Services"))
        self.eleveTab.setToolTip(_translate("galycDialog", "<html><head/><body><p>Ajouter un compte élève.</p></body></html>"))
        self.label_19.setText(_translate("galycDialog", "Créer un compte d\'élève"))
        self.groupBox_2.setTitle(_translate("galycDialog", "Elève"))
        self.label_2.setText(_translate("galycDialog", "Prénom"))
        self.label_6.setText(_translate("galycDialog", "Nom"))
        self.label_7.setText(_translate("galycDialog", "Login"))
        self.label_8.setText(_translate("galycDialog", "Classe"))
        self.label_9.setText(_translate("galycDialog", "Password"))
        self.eleveButton.setText(_translate("galycDialog", "Créer élève"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.eleveTab), _translate("galycDialog", "Elève"))
        self.profTab.setToolTip(_translate("galycDialog", "<html><head/><body><p>Ajouter un compte professeur.</p></body></html>"))
        self.label_18.setText(_translate("galycDialog", "Créer un compte de professeur"))
        self.groupBox.setTitle(_translate("galycDialog", "Professeur"))
        self.label.setText(_translate("galycDialog", "Prénom"))
        self.label_3.setText(_translate("galycDialog", "Nom"))
        self.label_4.setText(_translate("galycDialog", "Login"))
        self.label_5.setText(_translate("galycDialog", "Courriel"))
        self.profButton.setText(_translate("galycDialog", "Créer professeur"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.profTab), _translate("galycDialog", "Professeur"))
        self.aboutButton.setText(_translate("galycDialog", "À propos"))
        self.closeButton.setText(_translate("galycDialog", "Fermer"))

import ressources_rc
